[profile.default]
out = "out"
libs = ["lib"]
solc_version = '0.8.21'
auto_detect_solc = false
via-ir = true
ir-optimized = true
asm = true
asm-optimized = true
optimize = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src"
]

# caches storage retrieved locally for certain chains and endpoints
# can also be restricted to `chains = ["optimism", "mainnet"]`
# by default all endpoints will be cached, alternative options are "remote" for only caching non localhost endpoints and "<regex>"
# to disable storage caching entirely set `no_storage_caching = true`
rpc_storage_caching = { chains = "all", endpoints = "all" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default.optimizer_details]
constantOptimizer = true
yul = true
deduplicate = true
cse = true
inliner = true
orderLiterals = true
#this sets the `yulDetails` of the `optimizer_details` for the `default` profile
[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'dhfoDgvulfnTUtnIf'
[rpc_endpoints]
linea = "https://rpc.goerli.linea.build"
#arbitrum = ""
base = "https://base-goerli.public.blastapi.io"
